import type { StylistTgClient } from './types'

export type AccountOnboardingSourceType = 'phone' | 'phone_bulk' | 'json_metadata' | 'tdlib_directory' | 'tdata_archive' | 'session_file' | 'reauth'
export type AccountOnboardingCapability = { source_type: AccountOnboardingSourceType; can_preview: boolean; can_validate_structure: boolean; can_materialize_session: boolean; requires_reauth: boolean; supports_bulk: boolean; supports_artifact_upload: boolean; risk_level: 'low' | 'medium' | 'high'; user_facing_support_level: 'full' | 'preview_only' | 'requires_reauth' | 'unsupported' }
export type AccountOnboardingPhoneInput = { phone_number: string; label?: string | null; position?: number }
export type AccountOnboardingBatchCreate = { idempotency_key: string; source_type: AccountOnboardingSourceType; label?: string | null; phone_items?: AccountOnboardingPhoneInput[]; metadata_json?: unknown; artifact_id?: string | null; filename?: string | null }
export type AccountOnboardingArtifactCreate = { idempotency_key: string; source_type: AccountOnboardingSourceType; filename: string; content_base64: string }
export type AccountOnboardingMutation = { idempotency_key: string }
export type AccountOnboardingConfirm = AccountOnboardingMutation & { confirmation: 'ADD_ACCOUNTS'; consent_accepted: boolean; consent_version: string }
export type AccountOnboardingBatch = { id: string; source_type: AccountOnboardingSourceType; status: string; label: string | null; counters: { total_count: number; valid_count: number; ready_count: number; failed_count: number; blocked_count: number; requires_reauth_count: number }; created_at: string; updated_at: string; consent_confirmed_at: string | null; confirmed_at: string | null; queued_at: string | null; started_at: string | null; completed_at: string | null; cancelled_at: string | null; failure_code: string | null; failure_message: string | null }
export type AccountOnboardingItem = { id: string; batch_id: string; account_id: string | null; auth_session_id: string | null; source_type: AccountOnboardingSourceType; position: number; status: string; phone_hint: string | null; username_hint: string | null; telegram_user_id_hint: string | null; label: string | null; validation_code: string | null; validation_message: string | null; risk_level: 'low' | 'medium' | 'high'; requires_reauth: boolean; last_error_code: string | null; last_error_message: string | null; created_at: string; updated_at: string; next_retry_at: string | null; next_action: string | null }
export type AccountOnboardingSnapshot = { batch: AccountOnboardingBatch; items: AccountOnboardingItem[]; capabilities: AccountOnboardingCapability[]; poll_again_in_ms: number; next_action: string | null }
export type AccountOnboardingArtifact = { id: string; source_type: AccountOnboardingSourceType; sha256: string; size_bytes: number; content_type_detected: string; status: string; created_at: string; expires_at: string; failure_code: string | null; failure_message: string | null }

export const createAccountOnboardingBatch = (client: StylistTgClient, payload: AccountOnboardingBatchCreate): Promise<AccountOnboardingSnapshot> => client.request('/api/account-onboarding-batches', { method: 'POST', body: JSON.stringify(payload) })
export const fetchAccountOnboardingBatch = (client: StylistTgClient, batchId: string): Promise<AccountOnboardingSnapshot> => client.request(`/api/account-onboarding-batches/${encodeURIComponent(batchId)}`)
export const validateAccountOnboardingBatch = (client: StylistTgClient, batchId: string, payload: AccountOnboardingMutation): Promise<AccountOnboardingSnapshot> => client.request(`/api/account-onboarding-batches/${encodeURIComponent(batchId)}/validate`, { method: 'POST', body: JSON.stringify(payload) })
export const confirmAccountOnboardingBatch = (client: StylistTgClient, batchId: string, payload: AccountOnboardingConfirm): Promise<AccountOnboardingSnapshot> => client.request(`/api/account-onboarding-batches/${encodeURIComponent(batchId)}/confirm`, { method: 'POST', body: JSON.stringify(payload) })
export const cancelAccountOnboardingBatch = (client: StylistTgClient, batchId: string, payload: AccountOnboardingMutation): Promise<AccountOnboardingSnapshot> => client.request(`/api/account-onboarding-batches/${encodeURIComponent(batchId)}/cancel`, { method: 'POST', body: JSON.stringify(payload) })
export const retryAccountOnboardingItem = (client: StylistTgClient, batchId: string, itemId: string, payload: AccountOnboardingMutation): Promise<AccountOnboardingItem> => client.request(`/api/account-onboarding-batches/${encodeURIComponent(batchId)}/items/${encodeURIComponent(itemId)}/retry`, { method: 'POST', body: JSON.stringify(payload) })
export const submitAccountOnboardingCode = (client: StylistTgClient, batchId: string, itemId: string, payload: AccountOnboardingMutation & { code: string }): Promise<AccountOnboardingItem> => client.request(`/api/account-onboarding-batches/${encodeURIComponent(batchId)}/items/${encodeURIComponent(itemId)}/code`, { method: 'POST', body: JSON.stringify(payload) })
export const submitAccountOnboardingPassword = (client: StylistTgClient, batchId: string, itemId: string, payload: AccountOnboardingMutation & { password: string }): Promise<AccountOnboardingItem> => client.request(`/api/account-onboarding-batches/${encodeURIComponent(batchId)}/items/${encodeURIComponent(itemId)}/password`, { method: 'POST', body: JSON.stringify(payload) })
export const uploadAccountOnboardingArtifact = (client: StylistTgClient, payload: AccountOnboardingArtifactCreate): Promise<AccountOnboardingArtifact> => client.request('/api/account-onboarding-artifacts', { method: 'POST', body: JSON.stringify(payload) })
