from __future__ import annotations

AUTH_QUEUE_NAME = "auth_jobs"
PROFILE_QUEUE_NAME = "profile_jobs"
MEDIA_QUEUE_NAME = "media_jobs"
STORY_QUEUE_NAME = "story_jobs"
ACCOUNT_LIFECYCLE_QUEUE_NAME = "account_lifecycle_jobs"
MAINTENANCE_QUEUE_NAME = "maintenance_jobs"
SCHEDULER_QUEUE_NAME = "scheduler_jobs"
WARMUP_QUEUE_NAME = "warmup_jobs"
WARMUP_DISPATCH_QUEUE_NAME = "warmup_dispatch_jobs"
NEURO_COMMENT_QUEUE_NAME = "neuro_comment_jobs"

PRODUCTION_QUEUE_NAMES = (
    AUTH_QUEUE_NAME,
    PROFILE_QUEUE_NAME,
    MEDIA_QUEUE_NAME,
    STORY_QUEUE_NAME,
    ACCOUNT_LIFECYCLE_QUEUE_NAME,
    MAINTENANCE_QUEUE_NAME,
    SCHEDULER_QUEUE_NAME,
    WARMUP_QUEUE_NAME,
    WARMUP_DISPATCH_QUEUE_NAME,
    NEURO_COMMENT_QUEUE_NAME,
)

__all__ = [
    "ACCOUNT_LIFECYCLE_QUEUE_NAME",
    "AUTH_QUEUE_NAME",
    "MAINTENANCE_QUEUE_NAME",
    "MEDIA_QUEUE_NAME",
    "NEURO_COMMENT_QUEUE_NAME",
    "PROFILE_QUEUE_NAME",
    "PRODUCTION_QUEUE_NAMES",
    "SCHEDULER_QUEUE_NAME",
    "STORY_QUEUE_NAME",
    "WARMUP_DISPATCH_QUEUE_NAME",
    "WARMUP_QUEUE_NAME",
]
